version: '3.7'
services:
  jenkins:
    image: jenkins:jenkins:lts
    ports:
      - 2602:8080
      - 3602:50000
    volumes:
      - jenkins_data:/var/jenkins_home
    extra_hosts:
      - "swarm-manager:ipAdress"
    networks:
    - dockerNet

volumes:
  jenkins_data:

networks:
  dockerNet:
    external: true
