version: '3.7'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 2603:8080
      - 3603:50000
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - jenkins_data:/var/jenkins_home
    extra_hosts:
      - "swarm-manager:192.168.0.111"
    networks:
    - dockerNet

volumes:
  jenkins_data:

networks:
  dockerNet:
