version: '3.0'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    restart: always
    hostname: zookeeper
  kafka:
    image: bitnami/kafka:latest
    ports: 
      - пш"9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.111
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - zookeeper
  web:
    image: elkozmon/zoonavigator-web:latest
    ports:
      - "8015:8000"
    environment:
      WEB_HTTP_PORT : 8000
      API_HOST: "api"
      API_PORT : 9015
    depends_on:
      - api
    restart: always
  api:
    image: elkozmon/zoonavigator-api:latest
    environment:
      API_HTTP_PORT: 9000
    restart: always
    depends_on:
      - zookeeper